── 7дц▒√	W
FBS 001.000RFB 003.003
─ ─(0дц▒√	:TigerVNC (3169e14a6716)B  (Ъ0Ъ8Ъ@H	лП ┌	╩П ┼	≈П ▓	СЛ ⌡	мЕ ё	═ш ╗	Ся ╠	ае ╧	▌╧ ю	э╜ и	ф╘ п	°╒ ы	Т° А	я≤ И	ц≤ Я	╗√ Ы	⌠∙ │	▀∙ ┴}∙ ▒q∙ ≥m∙ ё`∙ ╙^∙ ╧Z∙ ╧W∙ аT■ йR■ яQ■ зP■ АP⌠ КO⌠ ЯO▓ ШO▓ │O░ ┴O░ ▒O▐  O▌ ║O█ ╚O▄ юP▄ б
P▄ ёP▄ и	P▄ й	P▄ ТP▌ ШP▐ ┐P░ ▀P▓ ⌠P⌠ ⌡O■ ёO■ ╛O∙ ЁO∙ ╩O∙ цO∙ сN∙ ЦN∙ КN∙ СN■ ШM■ ┐M⌠ ▄L⌠ ■K▓ °K▒ ╓J▒ ╛I░ ЁH▐ ╩G▐ цE▌ лD▌ тC▌ эC▌ ДC█ ЛB█ ЖB█ ┘
B█ ▄B█ ╪B█ ╪B█ ╧B▐ ╧B░ оB▒ оB▓ оA■ жA∙ ъA≈ ЛA≤ ПA≤ ЖA≥ Ч@  ├@⌡ ▌@⌡ ╧@° ╨@² ╨@² ╨@· ╨@· ╬@÷ г@÷ н@═ ж@║ П@║ С@║ С@╒ Ж@╒ Ч@╒ ├@╒ ▐
@╒ Ы@╒ ─@╒ │@ё ╖@╓ ╗@╔ ╟@╕ ╦@╕ ю@╖ х@╖ п@╖ э?╖ А?╖ ┬?╕ ░?╕ ≤?╓ ═>ё ╗>╒ ╟>║ ╦>÷ ю>² п=⌡ р=≥ ь=≈ Ю=√ П=■ Я=▓ Ь=▒ ─ <░ ┴ <▐ ▒ <▌ ╒ <█ ╢ <█ ╦ <█ ц 
<█ Д <█ ▀"<█ ▀"<█ Л(<▐ С(=▒ Ш(>⌠ ┐)?∙ ▀)@≈ ⌠)A≥ ⌡)B  ё)C° ╚)D² Ё)D· ╩)E÷ д)E÷ к)E═ с)E═ ш)E═ Ц)E═ К)
E═ ▄*E═ ╓+E═ ╓+E═ ╝.E═ ╣.D═ ╫.D═ е.C═ м.C═ у.C═ щ.B÷ Е.A· Л.?· У.>² Щ.<⌡ ┘/:≥ █/8≈ ≈/6√ ²/4■ ╔/2▓ ╜/0░ ╣/0▐ ╫/.█ е/-▄ м/,▀ в/+┴ Ц/*┬ Ф/)┬ М/)┤ У/)┤ Щ/(├ ┘0(├ █0
(├ ╬0(├ ∙2(├ ∙2)├ ╖6*├ ╞6,├ ╥6.┤ ©61┬ г64┼ р67▀ в6<▐ Х6?▒ О6A▓ Ы6C⌠ Ъ6D■ ┤7F∙ ▐7G√ ≈7J≤ ═7J≥ ╖7K≥ ╟7L  ╥7M  ©7M⌡ г7N⌡ о7N° в7O° Ю7O° И7O° О7O² В7P² Ъ7P² ┤8P² ▐8
P² ┤9P² ┬:P² ┬:P² ▒=O² ≥=N² ╒=M· ╘=L· ╠=K· ╧=K· а=J· и=J· я=I· ы=H² А=G° И=F⌡ Я=E  Ы=C≤ │>B≈ ┴>@∙ ▒>?⌠ ⌡>>▒ ║><▌ ╘>:▄ ю>9┼ а>9┬ и>8┬ я>8┤ ы>8├ А>7├ И>7├ Я>7┘ Ы>
7┘ Ё?7┘ з@7┘ з@9┘ ╛F:┘ ╢F;├ ╪F<┤ еF>┬ лF?┼ тFA▀ щFB█ ДFC▌ ЛFD▐ ТFE░ ЭFF▒ └GH⌠ ▄GI■ ■GJ∙ °GK≈ ╓GL≤ ╛GM≥ ╢GM  ╬GN⌡ дGO° лGO² тGP² эGP· ДGQ· МG
Q· ■HQ· ╓IQ· ╓IP÷ ╟LO║ ╤LN╒ ╬LL╓ фLK╕ нLI╗ уLH╘ чLG╙ ФLG╚ НLF╛ ЖLE╜ ЧLE╜ ├ME╜ █ME╜ ≈MD╜ ╕MD╜ ╤MD╜ фMD╛ нMC╛ жMC╚ чMB╙ ФMA╘ НM@╖ ЖM?╔ ЪM>ё ├N<║ ▌N:· ёN8° ╖N7  ╝N6≥ ╤N5≤ ╬N5≈ фN4√ нN4√ вN3√ ъN3∙ ГN3∙ ОN
3∙ ÷O3∙ вP3∙ вP3■ ьT1▒ ИT/█ ИT)└ ЯT$z ЬTn ┐U_ ┬UV ░UO ≤UD ═U@ ╗U: ╪U4 ╪U/ мU- яU, ыU, АU+ ИU+ ЯU+ ЗU+ │V* ┴V* ≥X( ║X% ╘X# ╠X! ╧X аX кX яX зX АX ИX ЯX
 ЫX │Y ┴Y ▒Y ≥Y ╒Y ╙Y ╠Y ╨Y аY яY ыY БY ЙY	 ЯY	 ЗY	 ЗY