// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Demonstration struct {
	Batches              []*Batch `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demonstration) Reset()         { *m = Demonstration{} }
func (m *Demonstration) String() string { return proto.CompactTextString(m) }
func (*Demonstration) ProtoMessage()    {}
func (*Demonstration) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Demonstration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demonstration.Unmarshal(m, b)
}
func (m *Demonstration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demonstration.Marshal(b, m, deterministic)
}
func (m *Demonstration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demonstration.Merge(m, src)
}
func (m *Demonstration) XXX_Size() int {
	return xxx_messageInfo_Demonstration.Size(m)
}
func (m *Demonstration) XXX_DiscardUnknown() {
	xxx_messageInfo_Demonstration.DiscardUnknown(m)
}

var xxx_messageInfo_Demonstration proto.InternalMessageInfo

func (m *Demonstration) GetBatches() []*Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

type Batch struct {
	Iterators            []*Events `protobuf:"bytes,1,rep,name=iterators,proto3" json:"iterators,omitempty"`
	Timestamp            uint32    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetIterators() []*Events {
	if m != nil {
		return m.Iterators
	}
	return nil
}

func (m *Batch) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Events struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Event                []byte   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*Demonstration)(nil), "proto.Demonstration")
	proto.RegisterType((*Batch)(nil), "proto.Batch")
	proto.RegisterType((*Events)(nil), "proto.Events")
	proto.RegisterType((*Event)(nil), "proto.Event")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x40, 0x51, 0x5b, 0xb9, 0xf8, 0x6a, 0x2f, 0x47, 0x07, 0x0f, 0x2d, 0x18, 0x51, 0x8a, 0xa1,
	0xe0, 0xa1, 0x19, 0xb2, 0x9b, 0xe4, 0x07, 0xf4, 0x07, 0x72, 0x72, 0x10, 0x0f, 0xb2, 0x8c, 0x74,
	0x04, 0xf2, 0xf7, 0x21, 0x67, 0x1b, 0x43, 0x26, 0xe9, 0xde, 0xbb, 0x07, 0x07, 0x70, 0x26, 0x1f,
	0xda, 0x29, 0x06, 0x0e, 0xa8, 0xe5, 0x31, 0x7b, 0x28, 0x0f, 0xe4, 0xc3, 0x98, 0x38, 0x3a, 0x1e,
	0xc2, 0x88, 0xbf, 0xf0, 0xde, 0x3b, 0x3e, 0x5d, 0x28, 0x55, 0xaa, 0x7e, 0x6d, 0x3e, 0xfe, 0x8b,
	0x39, 0x68, 0xbb, 0x07, 0xb5, 0xab, 0x34, 0x16, 0xb4, 0x10, 0xfc, 0x83, 0x7c, 0x60, 0x8a, 0x8e,
	0x43, 0x5c, 0x93, 0x72, 0x49, 0x8e, 0x57, 0x1a, 0x39, 0xd9, 0xcd, 0xe3, 0x17, 0xe4, 0x3c, 0x78,
	0x4a, 0xec, 0xfc, 0x54, 0xbd, 0xd4, 0xaa, 0x29, 0xed, 0x06, 0x4c, 0x07, 0xd9, 0x9c, 0x20, 0xc2,
	0x1b, 0xdf, 0x26, 0x92, 0x95, 0xdc, 0xca, 0x1f, 0x7f, 0x20, 0x23, 0xb1, 0x4f, 0x87, 0x49, 0x62,
	0x17, 0x67, 0xbe, 0x41, 0x0b, 0xc0, 0x4f, 0xd0, 0x82, 0x2a, 0x55, 0xab, 0xa6, 0xb0, 0xf3, 0xd0,
	0x67, 0xd2, 0xec, 0xee, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xf8, 0x56, 0xc8, 0x0b, 0x01, 0x00,
	0x00,
}
