// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Demonstration struct {
	Batches              []*Batch `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demonstration) Reset()         { *m = Demonstration{} }
func (m *Demonstration) String() string { return proto.CompactTextString(m) }
func (*Demonstration) ProtoMessage()    {}
func (*Demonstration) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Demonstration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demonstration.Unmarshal(m, b)
}
func (m *Demonstration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demonstration.Marshal(b, m, deterministic)
}
func (m *Demonstration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demonstration.Merge(m, src)
}
func (m *Demonstration) XXX_Size() int {
	return xxx_messageInfo_Demonstration.Size(m)
}
func (m *Demonstration) XXX_DiscardUnknown() {
	xxx_messageInfo_Demonstration.DiscardUnknown(m)
}

var xxx_messageInfo_Demonstration proto.InternalMessageInfo

func (m *Demonstration) GetBatches() []*Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

type Batch struct {
	Iterators            []*Events `protobuf:"bytes,1,rep,name=iterators,proto3" json:"iterators,omitempty"`
	Timestamp            string    `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetIterators() []*Events {
	if m != nil {
		return m.Iterators
	}
	return nil
}

func (m *Batch) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type StartTime struct {
	Time                 uint32   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTime) Reset()         { *m = StartTime{} }
func (m *StartTime) String() string { return proto.CompactTextString(m) }
func (*StartTime) ProtoMessage()    {}
func (*StartTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *StartTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTime.Unmarshal(m, b)
}
func (m *StartTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTime.Marshal(b, m, deterministic)
}
func (m *StartTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTime.Merge(m, src)
}
func (m *StartTime) XXX_Size() int {
	return xxx_messageInfo_StartTime.Size(m)
}
func (m *StartTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTime.DiscardUnknown(m)
}

var xxx_messageInfo_StartTime proto.InternalMessageInfo

func (m *StartTime) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Events struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Event                []byte   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

type Headers struct {
	MessageId            uint32   `protobuf:"varint,2,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ParentMessageId      uint32   `protobuf:"varint,3,opt,name=ParentMessageId,proto3" json:"ParentMessageId,omitempty"`
	EpisodeId            uint32   `protobuf:"varint,4,opt,name=EpisodeId,proto3" json:"EpisodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Headers) Reset()         { *m = Headers{} }
func (m *Headers) String() string { return proto.CompactTextString(m) }
func (*Headers) ProtoMessage()    {}
func (*Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{5}
}

func (m *Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Headers.Unmarshal(m, b)
}
func (m *Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Headers.Marshal(b, m, deterministic)
}
func (m *Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Headers.Merge(m, src)
}
func (m *Headers) XXX_Size() int {
	return xxx_messageInfo_Headers.Size(m)
}
func (m *Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Headers proto.InternalMessageInfo

func (m *Headers) GetMessageId() uint32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Headers) GetParentMessageId() uint32 {
	if m != nil {
		return m.ParentMessageId
	}
	return 0
}

func (m *Headers) GetEpisodeId() uint32 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

type Body struct {
	EnvId                string   `protobuf:"bytes,1,opt,name=EnvId,proto3" json:"EnvId,omitempty"`
	EnvStatus            string   `protobuf:"bytes,2,opt,name=EnvStatus,proto3" json:"EnvStatus,omitempty"`
	Fps                  float32  `protobuf:"fixed32,3,opt,name=Fps,proto3" json:"Fps,omitempty"`
	Reward               float32  `protobuf:"fixed32,4,opt,name=Reward,proto3" json:"Reward,omitempty"`
	Done                 bool     `protobuf:"varint,5,opt,name=Done,proto3" json:"Done,omitempty"`
	Record               bool     `protobuf:"varint,6,opt,name=Record,proto3" json:"Record,omitempty"`
	Obs                  string   `protobuf:"bytes,7,opt,name=Obs,proto3" json:"Obs,omitempty"`
	ObsType              string   `protobuf:"bytes,8,opt,name=ObsType,proto3" json:"ObsType,omitempty"`
	Info                 string   `protobuf:"bytes,9,opt,name=Info,proto3" json:"Info,omitempty"`
	InfoType             string   `protobuf:"bytes,10,opt,name=InfoType,proto3" json:"InfoType,omitempty"`
	Message              string   `protobuf:"bytes,11,opt,name=Message,proto3" json:"Message,omitempty"`
	Seed                 uint32   `protobuf:"varint,12,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Action               []byte   `protobuf:"bytes,13,opt,name=Action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{6}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *Body) GetEnvStatus() string {
	if m != nil {
		return m.EnvStatus
	}
	return ""
}

func (m *Body) GetFps() float32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *Body) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *Body) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Body) GetRecord() bool {
	if m != nil {
		return m.Record
	}
	return false
}

func (m *Body) GetObs() string {
	if m != nil {
		return m.Obs
	}
	return ""
}

func (m *Body) GetObsType() string {
	if m != nil {
		return m.ObsType
	}
	return ""
}

func (m *Body) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Body) GetInfoType() string {
	if m != nil {
		return m.InfoType
	}
	return ""
}

func (m *Body) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Body) GetSeed() uint32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *Body) GetAction() []byte {
	if m != nil {
		return m.Action
	}
	return nil
}

type Message struct {
	Method               string   `protobuf:"bytes,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Headers              *Headers `protobuf:"bytes,2,opt,name=Headers,proto3" json:"Headers,omitempty"`
	Body                 *Body    `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{7}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Message) GetHeaders() *Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Message) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Demonstration)(nil), "proto.Demonstration")
	proto.RegisterType((*Batch)(nil), "proto.Batch")
	proto.RegisterType((*StartTime)(nil), "proto.StartTime")
	proto.RegisterType((*Events)(nil), "proto.Events")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Headers)(nil), "proto.Headers")
	proto.RegisterType((*Body)(nil), "proto.Body")
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xc1, 0x8a, 0xdb, 0x30,
	0x10, 0xc5, 0x49, 0xec, 0xc4, 0xe3, 0xb8, 0x2d, 0xa2, 0x14, 0x51, 0xb6, 0x6c, 0x30, 0xa5, 0x18,
	0x0a, 0x7b, 0x48, 0x0f, 0x3d, 0x37, 0x6c, 0x4a, 0x73, 0x58, 0xb6, 0x28, 0xf9, 0x01, 0x25, 0x9e,
	0x76, 0x7d, 0xb0, 0x65, 0x2c, 0x35, 0x25, 0xbf, 0xd0, 0xcf, 0xe9, 0x17, 0x2e, 0x33, 0x92, 0x1d,
	0xd8, 0x93, 0xe6, 0xbd, 0x99, 0x79, 0x33, 0xcc, 0x13, 0x40, 0x85, 0x8d, 0xb9, 0xeb, 0x7a, 0xe3,
	0x8c, 0x88, 0xf9, 0x29, 0xbe, 0x42, 0x7e, 0x8f, 0x8d, 0x69, 0xad, 0xeb, 0xb5, 0xab, 0x4d, 0x2b,
	0x3e, 0xc1, 0xfc, 0xa8, 0xdd, 0xe9, 0x09, 0xad, 0x8c, 0x56, 0xd3, 0x32, 0x5b, 0x2f, 0x7d, 0xc3,
	0xdd, 0x86, 0x58, 0x35, 0x24, 0x0b, 0x05, 0x31, 0x33, 0xe2, 0x33, 0xa4, 0xb5, 0xc3, 0x5e, 0x3b,
	0xd3, 0x0f, 0x2d, 0x79, 0x68, 0xd9, 0x9e, 0xb1, 0x75, 0x56, 0x5d, 0xf3, 0xe2, 0x06, 0x52, 0x57,
	0x37, 0x68, 0x9d, 0x6e, 0x3a, 0x39, 0x59, 0x45, 0x65, 0xaa, 0xae, 0x44, 0x71, 0x0b, 0xe9, 0xde,
	0xe9, 0xde, 0x1d, 0xea, 0x06, 0x85, 0x80, 0x19, 0x65, 0x64, 0xb4, 0x8a, 0xca, 0x5c, 0x71, 0x5c,
	0x6c, 0x20, 0xf1, 0x9a, 0x9c, 0xbd, 0x74, 0x18, 0x34, 0x38, 0x16, 0x1f, 0x21, 0x41, 0xce, 0xbe,
	0xd8, 0x9c, 0x5b, 0x54, 0xc8, 0x15, 0x1f, 0x20, 0x66, 0x42, 0xbc, 0x85, 0x98, 0x29, 0x9e, 0xb0,
	0x54, 0x1e, 0x14, 0x06, 0xe6, 0x3f, 0x50, 0x57, 0xe8, 0x97, 0x7d, 0x40, 0x6b, 0xf5, 0x6f, 0xdc,
	0x55, 0x3c, 0x28, 0x57, 0x57, 0x42, 0x94, 0xf0, 0xfa, 0xa7, 0xee, 0xb1, 0x75, 0xd7, 0x9a, 0x29,
	0xd7, 0xbc, 0xa4, 0x49, 0x67, 0xdb, 0xd5, 0xd6, 0x54, 0x54, 0x33, 0xf3, 0x3a, 0x23, 0x51, 0xfc,
	0x9f, 0xc0, 0x6c, 0x63, 0xaa, 0x0b, 0xed, 0xb3, 0x6d, 0xcf, 0xbb, 0x8a, 0xf7, 0x49, 0x95, 0x07,
	0xdc, 0xdc, 0x9e, 0xf7, 0x4e, 0xbb, 0x3f, 0x76, 0xb8, 0xd8, 0x48, 0x88, 0x37, 0x30, 0xfd, 0xde,
	0x59, 0x1e, 0x3c, 0x51, 0x14, 0x8a, 0x77, 0x90, 0x28, 0xfc, 0xab, 0x7b, 0x3f, 0x69, 0xa2, 0x02,
	0xa2, 0x83, 0xdd, 0x9b, 0x16, 0x65, 0xbc, 0x8a, 0xca, 0x85, 0xe2, 0xd8, 0xd7, 0x9e, 0x4c, 0x5f,
	0xc9, 0x84, 0xd9, 0x80, 0x48, 0xf5, 0xf1, 0x68, 0xe5, 0x9c, 0xa7, 0x51, 0x28, 0x24, 0xcc, 0x1f,
	0x8f, 0xf6, 0x40, 0x17, 0x5f, 0x30, 0x3b, 0x40, 0xd2, 0xdd, 0xb5, 0xbf, 0x8c, 0x4c, 0xbd, 0x11,
	0x14, 0x8b, 0xf7, 0xb0, 0xa0, 0x97, 0xcb, 0x81, 0xf9, 0x11, 0x93, 0x52, 0xb8, 0x8c, 0xcc, 0xbc,
	0x52, 0x80, 0xa4, 0xb4, 0x47, 0xac, 0xe4, 0xd2, 0x1b, 0x4e, 0x31, 0x6d, 0xf8, 0xed, 0x44, 0xff,
	0x52, 0xe6, 0x6c, 0x52, 0x40, 0xc5, 0xbf, 0x68, 0x94, 0xa1, 0x9a, 0x07, 0x74, 0x4f, 0x66, 0x38,
	0x5c, 0x40, 0xa2, 0x1c, 0x9d, 0xe4, 0xbb, 0x65, 0xeb, 0x57, 0xe1, 0x3f, 0x04, 0x56, 0x8d, 0x46,
	0xdf, 0x7a, 0x07, 0xf8, 0x8c, 0xd9, 0x3a, 0x1b, 0x3e, 0xbc, 0xa9, 0x2e, 0xca, 0x5b, 0x73, 0x03,
	0xe9, 0x61, 0xfc, 0xb6, 0xc1, 0xc1, 0x91, 0x38, 0x26, 0x5c, 0xff, 0xe5, 0x39, 0x00, 0x00, 0xff,
	0xff, 0x58, 0xf4, 0x00, 0xc0, 0x5f, 0x03, 0x00, 0x00,
}
